theme = "my-nord"

[editor]
line-number = "relative"
cursorline = true
rulers = [120]

[editor.statusline]
mode.normal = "ğŸ¶"
mode.insert = "ğŸš€"
mode.select = "ğŸ‘†"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.whitespace]
render = "all"

[editor.file-picker]
hidden = false

